//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_categoria
    {
        public tb_categoria()
        {
            this.tb_producto = new HashSet<tb_producto>();
        }
    
        public int idCategoria { get; set; }
        public string descCategoria { get; set; }
        public bool estadoCategoria { get; set; }
    
        public virtual ICollection<tb_producto> tb_producto { get; set; }
    }
}
