//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_producto
    {
        public tb_producto()
        {
            this.tb_ventaxproducto = new HashSet<tb_ventaxproducto>();
        }
    
        public int idProducto { get; set; }
        public string nomProducto { get; set; }
        public string descProducto { get; set; }
        public decimal precioProducto { get; set; }
        public int stockProducto { get; set; }
        public int idCategoria { get; set; }
        public bool estadoProducto { get; set; }
    
        public virtual tb_categoria tb_categoria { get; set; }
        public virtual ICollection<tb_ventaxproducto> tb_ventaxproducto { get; set; }
    }
}
