//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_usuario
    {
        public tb_usuario()
        {
            this.tb_venta = new HashSet<tb_venta>();
        }
    
        public int idUsuario { get; set; }
        public string correoUsuario { get; set; }
        public string claveUsuario { get; set; }
        public string nombresUsuario { get; set; }
        public string apePatUsuario { get; set; }
        public string apeMatUsuario { get; set; }
        public string dniUsuario { get; set; }
        public System.DateTime fecNacimientoUsuario { get; set; }
        public string telefonoUsuario { get; set; }
        public string celularUsuario { get; set; }
        public int idRol { get; set; }
        public bool verificadoUsuario { get; set; }
        public bool estadoUsuario { get; set; }
    
        public virtual tb_rol tb_rol { get; set; }
        public virtual ICollection<tb_venta> tb_venta { get; set; }
    }
}
