//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_venta
    {
        public tb_venta()
        {
            this.tb_ventaxproducto = new HashSet<tb_ventaxproducto>();
        }
    
        public int idVenta { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaVenta { get; set; }
        public bool estadoVenta { get; set; }
    
        public virtual tb_usuario tb_usuario { get; set; }
        public virtual ICollection<tb_ventaxproducto> tb_ventaxproducto { get; set; }
    }
}
