//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pruebas_Unitarias.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/BaseDeDatos.csdl|res://*/BaseDeDatos.ssdl|res://*/BaseDeDatos.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=petshop.cmx3tebmpefi.us-east-2.rds.amazonaws.com;initial catalog=bd_doge;persist security info=True;user id=master;password=admin.sae;MultipleActiveResultSets=True;App=EntityFramework&quot;")]
        public string bd_dogeEntitiesSqlServer {
            get {
                return ((string)(this["bd_dogeEntitiesSqlServer"]));
            }
        }
    }
}
